server:
  port: 8089
spring:
  application:
    name: tree
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://121.36.208.253:5432/linkTree
    username: postgres
    password: Sayi123450
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        enable_lazy_load_no_trans: false

